### ISSUE TITLE
Primeros Pasos

### ISSUE THREAD

**Issue by Tropicalrambler** [sihaysistema/labels#1]
1. Agregar boton custom a Production Plan DocType
2. Ese botón enlazarlo con el script python que generará el PDF con las etiquetas.
3. Este boton envía argumentos con los Items y Quantities de Production Plan

**Comment by monroy95** [comment]
Cambios exitosos ya empujados a la rama **master**

**Comment by Tropicalrambler** [comment]
Funcionando excelente!  gracias!
