### ISSUE TITLE
Result a Downloadable PDF

### ISSUE THREAD

**Issue by Tropicalrambler** [sihaysistema/labels#2]
El pdf que genera el script se descarga automaticamente

**Comment by monroy95** [comment]
Solución alterna: tras ser generado el pdf con los stickers se abrirá una nueva ventana en el navegador con la opción de imprimir o descargar, cambios funcionando en la rama **master** especificamente en el commit **90d2ec8c1198d9e776eb08475351be5469db6a7e**

**Comment by Tropicalrambler** [comment]
Perfecta solución!  quedo al 100
